"""added specific transactions

Revision ID: c1cf990e3bea
Revises: d6b3d1d71508
Create Date: 2025-12-30 20:24:45.130844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c1cf990e3bea'
down_revision: Union[str, Sequence[str], None] = 'd6b3d1d71508'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crypto_transactions',
    sa.Column('crypto_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price_per_one', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.CheckConstraint('amount > 0', name='amount_positive'),
    sa.CheckConstraint('price_per_one > 0', name='price_per_one_positive'),
    sa.CheckConstraint('total_price > 0', name='total_price_positive'),
    sa.ForeignKeyConstraint(['crypto_id'], ['cryptos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_transactions',
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price_per_one', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.CheckConstraint('amount > 0', name='amount_positive'),
    sa.CheckConstraint('price_per_one > 0', name='price_per_one_positive'),
    sa.CheckConstraint('total_price > 0', name='total_price_positive'),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('transactions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('creation_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('price_per_one', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=False),
    sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_price', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('amount_positive')),
    sa.CheckConstraint('price_per_one > 0::numeric', name=op.f('price_per_one_positive')),
    sa.CheckConstraint('total_price > 0::numeric', name=op.f('total_price_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('transactions_pkey'))
    )
    op.drop_table('stock_transactions')
    op.drop_table('crypto_transactions')
    # ### end Alembic commands ###
