"""initial

Revision ID: d6b3d1d71508
Revises: 
Create Date: 2025-12-30 19:56:07.544909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6b3d1d71508'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cryptos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('updation_date', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('LENGTH(ticker) > 0 AND LENGTH(ticker) < 8', name='ticker_length'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker')
    )
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('updation_date', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('LENGTH(ticker) > 0 AND LENGTH(ticker) < 8', name='ticker_length'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price_per_one', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.CheckConstraint('amount > 0', name='amount_positive'),
    sa.CheckConstraint('price_per_one > 0', name='price_per_one_positive'),
    sa.CheckConstraint('total_price > 0', name='total_price_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('stocks')
    op.drop_table('cryptos')
    # ### end Alembic commands ###
